/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pe.edu.upeu.tresenraya;

import java.awt.Color;
import pe.edu.upeu.tresenraya.juegologica;

/**
 *
 * @author DELL
 */
public class ventana extends javax.swing.JFrame {

    /** Creates new form panel */
       public ventana() {
        initComponents();
        llenar();
        panelO.setBackground(Color.WHITE);
        panelX.setBackground(Color.yellow);
        diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        izquierda_vertical.setVisible(false);
        derecha_vertical.setVisible(false);
        centro.setVisible(false);
        medio_vertical.setVisible(false);
        abajo.setVisible(false);
        arriba.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        diagonal1 = new javax.swing.JLabel();
        diagonal2 = new javax.swing.JLabel();
        izquierda_vertical = new javax.swing.JPanel();
        medio_vertical = new javax.swing.JPanel();
        derecha_vertical = new javax.swing.JPanel();
        arriba = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        abajo = new javax.swing.JPanel();
        b02 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b00 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelX = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jx = new javax.swing.JLabel();
        panelO = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diagonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen1.png"))); // NOI18N
        jPanel1.add(diagonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 470, 420));

        diagonal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen2.png"))); // NOI18N
        jPanel1.add(diagonal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 160, 520, 310));

        izquierda_vertical.setBackground(new java.awt.Color(255, 0, 0));
        izquierda_vertical.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout izquierda_verticalLayout = new javax.swing.GroupLayout(izquierda_vertical);
        izquierda_vertical.setLayout(izquierda_verticalLayout);
        izquierda_verticalLayout.setHorizontalGroup(
            izquierda_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        izquierda_verticalLayout.setVerticalGroup(
            izquierda_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(izquierda_vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 310));

        medio_vertical.setBackground(new java.awt.Color(255, 0, 0));
        medio_vertical.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout medio_verticalLayout = new javax.swing.GroupLayout(medio_vertical);
        medio_vertical.setLayout(medio_verticalLayout);
        medio_verticalLayout.setHorizontalGroup(
            medio_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        medio_verticalLayout.setVerticalGroup(
            medio_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(medio_vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 310));

        derecha_vertical.setBackground(new java.awt.Color(255, 0, 0));
        derecha_vertical.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout derecha_verticalLayout = new javax.swing.GroupLayout(derecha_vertical);
        derecha_vertical.setLayout(derecha_verticalLayout);
        derecha_verticalLayout.setHorizontalGroup(
            derecha_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        derecha_verticalLayout.setVerticalGroup(
            derecha_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(derecha_vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 310));

        arriba.setBackground(new java.awt.Color(255, 0, 0));
        arriba.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout arribaLayout = new javax.swing.GroupLayout(arriba);
        arriba.setLayout(arribaLayout);
        arribaLayout.setHorizontalGroup(
            arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        arribaLayout.setVerticalGroup(
            arribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 340, 20));

        centro.setBackground(new java.awt.Color(255, 0, 0));
        centro.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout centroLayout = new javax.swing.GroupLayout(centro);
        centro.setLayout(centroLayout);
        centroLayout.setHorizontalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        centroLayout.setVerticalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 20));

        abajo.setBackground(new java.awt.Color(255, 0, 0));
        abajo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout abajoLayout = new javax.swing.GroupLayout(abajo);
        abajo.setLayout(abajoLayout);
        abajoLayout.setHorizontalGroup(
            abajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        abajoLayout.setVerticalGroup(
            abajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 330, 20));

        b02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b02ActionPerformed(evt);
            }
        });
        jPanel1.add(b02, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 131, 107, 100));

        b01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b01ActionPerformed(evt);
            }
        });
        jPanel1.add(b01, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 131, 105, 100));

        b00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b00ActionPerformed(evt);
            }
        });
        jPanel1.add(b00, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 131, 106, 100));

        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 237, 106, 100));

        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 237, 105, 100));

        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 237, 107, 100));

        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        jPanel1.add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 106, 100));

        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        jPanel1.add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 105, 100));

        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        jPanel1.add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 107, 100));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Shirt & Tie Demo", 0, 48)); // NOI18N
        jLabel1.setText("TRES EN RAYA (MICHI)");
        jLabel1.setIconTextGap(68);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 750, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setText("Jugar de nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("X");

        jx.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jx.setForeground(new java.awt.Color(255, 0, 0));
        jx.setText("0");

        javax.swing.GroupLayout panelXLayout = new javax.swing.GroupLayout(panelX);
        panelX.setLayout(panelXLayout);
        panelXLayout.setHorizontalGroup(
            panelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jx)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelXLayout.setVerticalGroup(
            panelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jx))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("O");

        jo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jo.setForeground(new java.awt.Color(0, 0, 102));
        jo.setText("0");

        javax.swing.GroupLayout panelOLayout = new javax.swing.GroupLayout(panelO);
        panelO.setLayout(panelOLayout);
        panelOLayout.setHorizontalGroup(
            panelOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jo)
                .addGap(39, 39, 39))
        );
        panelOLayout.setVerticalGroup(
            panelOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jo))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(panelO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b00ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal1, 7, 0, 0);
        l.rayar(matriz, arriba, 1, 0, 0);
        l.rayar(matriz, izquierda_vertical, 4, 0, 0);
        
        if(l.ejecutar(b00, 0, 0, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b00ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal2, 8, 1,1);
        l.rayar(matriz, diagonal1, 7, 1, 1);
        l.rayar(matriz, medio_vertical, 5, 1, 1);
        l.rayar(matriz, centro, 2, 1, 1);
        if(l.ejecutar(b11, 1,1, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, medio_vertical, 2, 2,2);
        l.rayar(matriz, diagonal1, 7, 2,2);
        l.rayar(matriz, derecha_vertical, 6, 2, 2);
        l.rayar(matriz, abajo, 3, 2, 2);
        if(l.ejecutar(b22, 2,2, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b22ActionPerformed

    private void b01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b01ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, arriba, 1, 0, 1);
        l.rayar(matriz, centro, 2, 0, 1);
        l.rayar(matriz, medio_vertical, 5, 0, 1);
        if(l.ejecutar(b01, 0,1, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b01ActionPerformed

    private void b02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b02ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal2, 8, 0,2);
        l.rayar(matriz, arriba, 1, 0, 2);
        l.rayar(matriz, derecha_vertical, 6, 0, 2);
        
        if(l.ejecutar(b02, 0,2, matriz, jx, jo)==1){
            reiniciar();
        }
    }//GEN-LAST:event_b02ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, centro, 2, 1, 0);
        l.rayar(matriz, izquierda_vertical, 4, 1, 0);
        if(l.ejecutar(b10, 1,0, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b10ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        turnoar();
        
        l.rayar(matriz, derecha_vertical, 6, 1,2);
        l.rayar(matriz, centro, 2, 1, 2);

        if(l.ejecutar(b12, 1,2, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b12ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, diagonal2, 8, 2,0);
        l.rayar(matriz, abajo, 2, 2,0);
        l.rayar(matriz, izquierda_vertical, 4, 2, 0);
        l.rayar(matriz, abajo, 3, 2, 0);
        if(l.ejecutar(b20, 2,0, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        turnoar();
        l.rayar(matriz, abajo, 2, 2,1);
        l.rayar(matriz, medio_vertical, 5, 2, 1);
        l.rayar(matriz, abajo, 3, 2, 1);
        if(l.ejecutar(b21, 2,1, matriz, jx, jo)==1){
            reiniciar();
        } 
    }//GEN-LAST:event_b21ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reiniciar();
    }//GEN-LAST:event_jButton1ActionPerformed
int matriz[][]=new int[3][3];
public void llenar(){
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            matriz[i][j]=(j+10)*(i+10);
        }
    }
}
juegologica l=new juegologica(0,0,0);

public void turnoar(){
    if(l.getTurno()==1){
        panelX.setBackground(Color.pink);
        panelO.setBackground(Color.white);
    }
    if(l.getTurno()==0){
        panelX.setBackground(Color.white);
        panelO.setBackground(Color.pink);
    }
}
public void reiniciar(){
    llenar();
    b00.setText("");
    b00.setEnabled(true);
    b01.setText("");
    b01.setEnabled(true);
    b02.setText("");
    b02.setEnabled(true);
    b10.setText("");
    b10.setEnabled(true);
    b11.setText("");
    b11.setEnabled(true);
    b12.setText("");
    b12.setEnabled(true);
    b20.setText("");
    b20.setEnabled(true);
    b21.setText("");
    b21.setEnabled(true);
    b22.setText("");
    b22.setEnabled(true);
    diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        izquierda_vertical.setVisible(false);
        derecha_vertical.setVisible(false);
        medio_vertical.setVisible(false);
        centro.setVisible(false);
        abajo.setVisible(false);
        arriba.setVisible(false);
}


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abajo;
    private javax.swing.JPanel arriba;
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel derecha_vertical;
    private javax.swing.JLabel diagonal1;
    private javax.swing.JLabel diagonal2;
    private javax.swing.JPanel izquierda_vertical;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jo;
    private javax.swing.JLabel jx;
    private javax.swing.JPanel medio_vertical;
    private javax.swing.JPanel panelO;
    private javax.swing.JPanel panelX;
    // End of variables declaration//GEN-END:variables

}
